# Generated by Django 5.2.8 on 2025-11-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemimage'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE core_item ALTER COLUMN is_active SET DEFAULT true;",
            reverse_sql="ALTER TABLE core_item ALTER COLUMN is_active DROP DEFAULT;",
        ),
    ]
