# Generated by Django 5.2.8 on 2025-11-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fix_is_active_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
