# Generated by Django 5.2.8 on 2025-12-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
